README.md

This is an out-of-box React Native binding for ARKit.

Add react-native-arkit

---

README.md

Hi there! 
I added a link to simple measuring app repo and in articles section link to blog post with tutorial how to make that kind of app.
Regards,
Pawel

Measuring app with ARKit, project and blog post with tutorial

---

README.md

* ARKit weekly
* Made with ARKit

adding ARKit useful links

---

README.md

Here's a cool project to create 3D charts with ARKit.

Add ARCharts to README.md

---

README.md

Hello,
I've added 3DSnake game that I recently published. It's simple well known game snake. Player controls the movements of the snake by swiping left or right. The project demonstrates plane detection, scenekit, particle effects.
Thanks

Added 3DSnake game

---

README.md

Article added: Building an AR game with ARKit and Spritekit.
It's a topic not covered by other articles in the list. Thanks.

Article added about SpriteKit

---

README.md

I add another poject after first PR so the title may only have one project name.
I'll pay attention next time.

Add ARKit-CoreLocation

---

README.md

Using ARKit with Metal and Augmented Reality With ARKit For IOS

Add Article

---

README.md

Maybe we need to call @bjarnel to add some description and gifs in his README file.

Add arkit-smb-homage

---

README.md

[Shell Game](https://github.com/handsomecode/arkit-shell-game) is a sample game made with ARKit and SceneKit. There was not any ARKit Shell game before. It's exciting game developing concentration that is quite good sample of working with ARKit.

Add ShellGame to projects list

---

README.md

ARKit-Sample-ObjC application written in Objective C with features of Add, Remove, Scale, Move single or multiple objects with plane detection, reset session and support checking. I did digging a lot and see vary few example using objective c and hope it'll be helpful as all the features is in one place.

ARKit-Sample-ObjC added on readme

---

README.md

Added ARKit Core Location tutorial - part one.

ARKit Navigation Tutorial 

---

README.md

Add MeasureAdd and AppStore Multiply Project.

Add Projects and AppStore Projcet

---

README.md

Added an App Store app that lets you add phone pictures to your wall. It's unique in that it tracks vertical surfaces and is significantly useful.

Added app Wallr as an App Store app

---

README.md

Added tutorial link for making ARKit drone.

added ARKit drone tutorial link

---

README.md

This application allows to place TV on any horizontal surface and playback videos using various controls (play, pause, stop, previous/next video). There is also ability to scale, rotate, re-position TV.
Release tag with package can be found here: https://github.com/MaximAlien/ARPlayer/releases/tag/v0.1.0

Add ARPlayer project to projects list

---

README.md

Thanks for this list. I added our AR game Arcane Maze.
Please check out a demo of the app: https://www.youtube.com/watch?v=p69QW-6ghSU&t=1s

Add Arcane Maze to AppStore List 

---

README.md

ToolKit for Voxel graphic, using ARKit + SceneKit.
https://github.com/VoxxxelAR/ARVoxelKit

ARVoxelKit

---

README.md

Added ARKitSpitfire

---

README.md

Added ARKitAirport

---

README.md

It's nearly the same project as ARSolarPlay, but this one was built in Swift 4 instead of Objective C. Everything is in English and there are no Chinese comments in the code. The code is divided in easy to navigate short files instead of one 1000+ lines file.

Substituted solar system repo for a new one

---

README.md

Hi, for people with no Swift/ObjectC experience like me, Unity is much more easier to get started and create application quickly :)

Adding Build ARKit Application with Unity

---

README.md

Augmented Reality With ARKit: Detecting Planes

Add Tutorials

---

README.md

Added ARPiano - A augmented reality fine-tuned and professional piano app with 61 keys or 88 keys, which you can place every plane to play.

Added ARPiano

---

README.md

Reverts olucurious/Awesome-ARKit#62

Revert "Substituted solar system repo for a new one"

---

README.md

ARVideoKit enables developers to capture and record videos 📹, photos 🌄, Live Photos 🎇, and GIFs 🎆 with ARKit content.

Added ARVideoKit

---

README.md

uARKit is a swift framework on ARKit. It simplifies the usage of ARKit for non-AR developers and add more functionality. for example you can augment an Image file with method:
addImage(imageName: "http://example.com/bird.png", position: coordinate(top:0, right: 0, front:5))
It is an ongoing project there are more issues like adding 3D, cloud functionality etc.

add new project - uARKit

---

README.md

Thanks for **Awesome-ARKit**! ✌️

Add "AR Snake Simulator" to "AppStore" section

---

README.md

Add [ARBottleJump](https://github.com/songkuixi/ARBottleJump) - An ARKit version of WeChat Bottle Jump game.

Add ARBottleJump

---

README.md

Add [ARKit-Virtual-Backdrop](https://github.com/montaguegabe/Arkit-Virtual-Backdrop) - Superimpose your image into a 3D rendered world using Metal

Add ARKit-Virtual-Backdrop

---

README.md

Horizon Explorer works in a similar sort of way to "Sky Guide AR" (already on the list), but for landmarks on the ground.

Add Horizon Explorer

---

README.md

[For creating stunning soap bubbles in your AR app](https://github.com/AppPear/bubbleblower)

Added a new project called Bubble blower for stunning AR soap bubbles

---

README.md

Add entry for Pocket Balloon to AppStore list, including description and link

Add Pocket Balloon to the AppStore list

---

README.md

Hey there,
so I recently created [this quick](https://github.com/Bersaelor/WallStreaming) demo to illustrate how to use an `AVPlayer` in a SceneKit context, which ties in nicely with the new `.vertical` surface detection of ARKit.
What do you guys think?

WallStreaming - vertical surface detection

---

README.md

Mokapp2017_World: you can explore the world around you, play a video, put objects in front of you or to a plane (with gravity), play Space Invaders 3D.
Mokapp2017_Face: put objects and particles on your face.

Added Mokapp2017 projects

---

README.md

[Wavy Music](https://itunes.apple.com/us/app/wavy-music/id1366917156?ls=1&mt=8) - Experience music in augmented reality.

Add Wavy Music

---

README.md

* [AR Candle](https://itunes.apple.com/us/app/ar%E7%A5%88%E7%A6%8F/id1346647915?mt=8) - AR Candle is an augmented reality candle blessing app.

Add AR Candle

---

README.md

We have added below features of ARKit2.0 in this Prototype
1. Image tracking
2. Save and load maps
3. Detect objects
4. Environmental texturing

ARKit2 Prototype

---

README.md

Added a new AR app in the store section

Added Climbing AR app

---

README.md

[ARBusinessCard](https://github.com/BlackMirrorz/ARKitBusinessCard) - Create and view fully interactive business cards.

Add ARBusinessCard.

---

README.md

Augmented Reality Movie Trailer made with ARKit and SceneKit.

Add ARTrailer

---

README.md

Add the app entry for Snake.AR

Add Snake.AR app

---

README.md

Added iOS-Depth-Sampler which has an ARKit+Depth demo.

Add ARKit+Depth (iOS-Depth-Sampler)

---

README.md

- ARKit-Emperor
- GRAFFITY
- Pemoji

Add ARKit-Emperor, GRAFFITY, and Pemoji

---

.travis.yml
README.md

[Link to PortalMask Repo](https://github.com/maxxfrazer/SceneKit-PortalMask)
This repo contains a CocoaPod which can be used to create an occluded space with a non occluded window into it.
In the repo there is a `gif` example of how this can be used on tracking images.
I think this would be useful to people and plan on adding more basic shapes and later complex shapes to this. I've seen people creating similar things by using a series of geometries or including a .scn file. This solution is low in poly-count and tiny in disk storage.

PortalMask - Create Occluded space in SceneKit

---

README.md

Hello - Thanks for the awesome list - I've added just two projects from Nexus Studios - Hotstepper is probably still the only Augmented Reality character-based Wayfinding app on the store - and BBC Civilisations was featured at WWDC and is used as an example for UX design in AR

 added hotstepper & BBC Civilisations to apps

---

README.md

I feel like i submitted this weeks ago ? am i doing this wrong ?

add riksroom to app list

---

.github/workflows/awesome-test.yml
README.md

- Added usage of GitHub Actions
To be used instead of Travis as it's native to GitHub

Added GitHub Action

---

README.md

Reverts olucurious/Awesome-ARKit#144

Revert "Added resources and project."

---

README.md

Added tutorial to implement AR-Quick-Look in any iOS application.
Added tutorial to learn about the conversion of existing model to usdz format to use for your AR application.
Added project for AR-Quick-Look.

Added tutorials and project.

---

README.md

A new project named ARInstagram was added to the list of projects.

new repository suggestion - ARInstagram.

---

README.md

This app uses your phone's TrueDepth camera + ARKit to let you put your face in any real world wall: https://apps.apple.com/us/app/id1522257130

Add In The Walls App

---

README.md

[This Xcode project](https://github.com/mattbierner/reality-shaders-example) demonstrates how you can easily apply metal shaders to real world surfaces

Add Reality Shaders project

---

README.md

Unlike existing solutions, SCNRecorder doesn't take snapshots or use an additional rendering loop to capture pixel buffers. It reads already rendered pixel buffers of the scene and doesn't drop framerate.
https://github.com/gorastudio/SCNRecorder

Add SCNRecorder framework

---

README.md

This change adds the new [watAR app](https://apps.apple.com/us/app/watar/id1546980861) under the App Store section

Adding watAR app

---

README.md

Add Paint the City to App Store section

Add Paint the City app
